{
 "title": "TS-APP",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total HTTP requests duration ms bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_total_requests_duration_ms_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last HTTP request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "http_last_request_duration", "legendFormat": "__auto" }
   ]
  }
 ]
}